import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "./components/Provider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {





  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
      {
        typeof window !== 'undefined' && window.location.host === 'blog.creco.dev' ? (
          <>
            <Script async src="https://www.googletagmanager.com/gtag/js?id=G-4M82715ZRX"></Script>
            <Script type="text/javascript" children={`
              window.dataLayer = window.dataLayer || [];
              function gtag() {
                dataLayer.push(arguments); 
              }
              gtag('js', new Date());

              gtag('config', 'G-4M82715ZRX');
            `} />
          </>
        ) : null
      }
    </html >
  );
}
